typography_spectrum: 0.1615664
color:
  brandStrength: 0.3287051
  saturation: 0.3138496
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.3403509
  rhythmicContrast: 0.7978262
layout_spectrum: 0.9963259
name: Positive Energy Foundation
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
